name: Deploy PR previews
concurrency: preview-${{ github.ref }}
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          repository: osac/betadeploy
          token: ${{ secrets.MACHINE_USER_TOKEN }}
          event-type: osac-pr-preview-build
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "prId": "${{github.event.pull_request.number}}"}'
